# Generated by Django 3.2.4 on 2021-08-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=62, primary_key=True, serialize=False)),
                ('data', models.JSONField(null=True)),
                ('tracks', models.ManyToManyField(related_name='playlist_tracks', to='spotify.Track')),
            ],
        ),
        migrations.CreateModel(
            name='RecentTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TopTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='all_tracks',
            field=models.ManyToManyField(related_name='all', to='spotify.Track'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotify.track'),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='User', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='playlist_tracks',
            field=models.ManyToManyField(related_name='playlist', to='spotify.Track'),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_album_tracks',
            field=models.ManyToManyField(related_name='saved_album', to='spotify.Track'),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_albums',
            field=models.ManyToManyField(to='spotify.Album'),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_tracks',
            field=models.ManyToManyField(related_name='saved', to='spotify.Track'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_connected',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='top_artists',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='top_genres',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='toptrack',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AddField(
            model_name='toptrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.track'),
        ),
        migrations.AddField(
            model_name='recenttrack',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AddField(
            model_name='recenttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.track'),
        ),
        migrations.AddField(
            model_name='profile',
            name='playlists',
            field=models.ManyToManyField(to='account.Playlist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recent_tracks',
            field=models.ManyToManyField(related_name='recent', through='account.RecentTrack', to='spotify.Track'),
        ),
        migrations.AddField(
            model_name='profile',
            name='top_tracks',
            field=models.ManyToManyField(related_name='top', through='account.TopTrack', to='spotify.Track'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.image'),
        ),
    ]
