version: "3.8"

services:
  web:
    restart: on-failure
    container_name: name
    build: 
      context: ./
      dockerfile: ./Dockerfiles/dev/Dockerfile
    ports:
      - ${NAME_PORT}:${NAME_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    env_file:
      - env/.env.dev
    depends_on:
      - data
      - flower
      - redis
    entrypoint: ["./scripts/entrypoints/dev/main.sh"]
    networks:
      - app-network 

  data:
    container_name: data
    image: postgres:latest
    env_file:
      - env/.env.dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASS=${APP_DB_PASS}
      - APP_DB_NAME=${APP_DB_NAME}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - app-network 

  celery:
    restart: always
    build: 
      context: ./
      dockerfile: ./Dockerfiles/dev/Dockerfile
    env_file:
      - env/.env.dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${APP_DB_NAME}
      - DB_HOST=${POSTGRES_HOST}
      - DB_USER=${APP_DB_USER}
      - DB_PASS=${APP_DB_PASS}
      - DB_NAME=${APP_DB_NAME}
    depends_on:
      - rabbit
    entrypoint: ["./scripts/entrypoints/dev/celery.sh"]
    networks:
      - app-network 

  rabbit:
    restart: always
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    ports:
      - ${RABBIT_PORT}:${RABBIT_PORT}
    networks:
      - app-network 

  flower:
    build: 
      context: ./
      dockerfile: ./Dockerfiles/dev/Dockerfile
    image: mher/flower
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    env_file:
      - env/.env.dev
    environment: 
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on: 
      - rabbit
    entrypoint: ["./scripts/entrypoints/dev/flower.sh"]
    networks:
        - app-network

  redis:
    image: redis:6.0-buster
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app-network
    expose: 
      - ${REDIS_PORT}

networks:
  app-network:
    driver: bridge
    
volumes:
  data:
    external: true
  static:
    external: true
