#!/bin/bash
if [ ! -d "./data" ]; then
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v --username "$POSTGRES_USER" --dbname "$POSTGRES_USER" <<-EOSQL
  CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
  CREATE DATABASE $POSTGRES_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_NAME TO $POSTGRES_USER;
  \connect $POSTGRES_NAME $POSTGRES_USER
  
EOSQL
fi
