#!/bin/bash
if [ ! -d "./data" ]; then
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v --username "$POSTGRES_USER" --dbname "$POSTGRES_USER" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  
EOSQL
fi
